export {default as basket} from '@src/app/basket'
export {default as confirm} from '@src/containers/catalog-confirmation'
export {default as separateStore} from '@src/app/store-modal'
export {default as addExtraItems} from '@src/app/add-extra-items-modal'
export {default as article} from '@src/app/article-modal'
